package generator

import (
	"fmt"

	"gokit-init/internal/config"
)

// Generate orchestrates the entire project generation process
func Generate(cfg *config.ProjectConfig) error {
	fmt.Printf("\nGenerating project: %s\n\n", cfg.ProjectName)

	// Step 1: Create directory structure
	if err := CreateDirectoryStructure(cfg); err != nil {
		return fmt.Errorf("directory creation failed: %w", err)
	}

	// Step 2: Generate go.mod
	if err := GenerateGoMod(cfg); err != nil {
		return fmt.Errorf("go.mod generation failed: %w", err)
	}

	// Step 3: Generate main.go
	if err := GenerateMainFile(cfg); err != nil {
		return fmt.Errorf("main.go generation failed: %w", err)
	}

	// Step 4: Generate .env.example
	if err := GenerateEnvExample(cfg); err != nil {
		return fmt.Errorf(".env.example generation failed: %w", err)
	}

	// Step 5: Generate database configuration (if specified)
	if err := GenerateDatabaseConfig(cfg); err != nil {
		return fmt.Errorf("database config generation failed: %w", err)
	}

	// Step 6: Generate Docker files (if specified)
	if err := GenerateDockerFiles(cfg); err != nil {
		return fmt.Errorf("Docker files generation failed: %w", err)
	}

	// Step 7: Generate Clean Architecture files (if specified)
	if err := GenerateCleanArchFiles(cfg); err != nil {
		return fmt.Errorf("Clean Architecture files generation failed: %w", err)
	}

	// Step 8: Generate README
	if err := generateReadme(cfg); err != nil {
		return fmt.Errorf("README generation failed: %w", err)
	}

	fmt.Printf("\nProject '%s' generated successfully!\n", cfg.ProjectName)
	printNextSteps(cfg)

	return nil
}

func generateReadme(cfg *config.ProjectConfig) error {
	content := fmt.Sprintf(`# %s

A Go web application generated by gokit-init.

## Project Structure

`, cfg.ProjectName)

	if cfg.CleanArch {
		content += `This project follows Clean Architecture principles:

- ` + "`cmd/app/`" + ` - Application entry point
- ` + "`internal/domain/`" + ` - Business entities (domain models)
- ` + "`internal/repository/`" + ` - Data access layer
- ` + "`internal/service/`" + ` - Business logic layer
- ` + "`internal/handler/`" + ` - HTTP handlers
- ` + "`internal/config/`" + ` - Configuration
- ` + "`pkg/`" + ` - Public libraries

`
	} else {
		content += `This project uses a simple structure:

- ` + "`handler/`" + ` - HTTP handlers
- ` + "`domain/`" + ` - Domain models

`
	}

	content += `## Getting Started

1. Install dependencies:
   ` + "```bash" + `
   go mod tidy
   ` + "```" + `

2. Copy environment file:
   ` + "```bash" + `
   cp .env.example .env
   ` + "```" + `

3. Update ` + "`.env`" + ` with your configuration

`

	if cfg.Docker {
		content += `4. Run with Docker:
   ` + "```bash" + `
   docker-compose up --build
   ` + "```" + `

   Or run locally:
   ` + "```bash" + `
   go run `
		if cfg.CleanArch {
			content += `cmd/app/main.go`
		} else {
			content += `main.go`
		}
		content += `
   ` + "```" + `

`
	} else {
		content += `4. Run the application:
   ` + "```bash" + `
   go run `
		if cfg.CleanArch {
			content += `cmd/app/main.go`
		} else {
			content += `main.go`
		}
		content += `
   ` + "```" + `

`
	}

	content += `## API Endpoints

- ` + "`GET /health`" + ` - Health check endpoint
- ` + "`GET /`" + ` - Welcome endpoint

`

	if cfg.Database != "" {
		content += fmt.Sprintf(`## Database

This project is configured to use **%s**.

`, cfg.Database)
		if cfg.Database == "mysql" || cfg.Database == "postgres" {
			content += `Make sure your database server is running and update the connection details in ` + "`.env`" + `.

`
		}
	}

	content += `## License

MIT
`

	if err := WriteFile(cfg.ProjectName, "README.md", content); err != nil {
		return err
	}

	fmt.Println("Created README.md")
	return nil
}

func printNextSteps(cfg *config.ProjectConfig) {
	fmt.Println("\nNext steps:")
	fmt.Printf("   cd %s\n", cfg.ProjectName)
	fmt.Println("   go mod tidy")
	fmt.Println("   cp .env.example .env")

	if cfg.Docker {
		fmt.Println("   docker-compose up --build")
	} else {
		if cfg.CleanArch {
			fmt.Println("   go run cmd/app/main.go")
		} else {
			fmt.Println("   go run main.go")
		}
	}

	fmt.Println("\nHappy coding!\n")
}
